/* Batch: Unsupervised & Latent-Variable Models */
(window.QUIZ_BATCHES = window.QUIZ_BATCHES || {})["unsupervised"] = [
  {
    id: "uns-1", type: "mc", framing: "conceptual", difficulty: 1,
    prompt: "In a <b>finite mixture</b> $p(\\boldsymbol{x}_i\\mid\\boldsymbol\\theta)=\\sum_{k=1}^K\\pi_k\\,p_k(\\boldsymbol{x}_i\\mid\\boldsymbol\\theta_k)$, what constraint must the <b>mixing weights</b> $\\pi_k$ satisfy?",
    options: [
      "$\\pi_k\\ge0$ and $\\sum_k\\pi_k=1$",
      "$\\pi_k$ may be any real number",
      "$\\sum_k\\pi_k=K$",
      "Every $\\pi_k$ must equal $1/K$"
    ],
    answer: 0,
    explanation: "The mixing weights form a categorical distribution over the $K$ components, so they are non-negative and sum to one: $\\pi_k\\ge0,\\ \\sum_k\\pi_k=1$. They need not be uniform.",
    ref: "Latent variable models & mixtures"
  },
  {
    id: "uns-2", type: "mc", framing: "conceptual", difficulty: 1,
    prompt: "The <b>responsibility</b> $r_{ik}=p(z_i{=}k\\mid\\boldsymbol{x}_i)$ in a GMM represents which kind of cluster assignment?",
    options: [
      "A soft assignment — a probability that point $i$ belongs to component $k$",
      "A hard assignment — point $i$ is placed in exactly one cluster",
      "The Euclidean distance from $\\boldsymbol{x}_i$ to center $\\boldsymbol\\mu_k$",
      "The number of points assigned to component $k$"
    ],
    answer: 0,
    explanation: "$r_{ik}=\\frac{\\pi_k\\mathcal{N}(\\boldsymbol{x}_i\\mid\\boldsymbol\\mu_k,\\boldsymbol\\Sigma_k)}{\\sum_{k'}\\pi_{k'}\\mathcal{N}(\\boldsymbol{x}_i\\mid\\boldsymbol\\mu_{k'},\\boldsymbol\\Sigma_{k'})}$ is the posterior probability that $\\boldsymbol{x}_i$ was generated by component $k$ — a soft assignment in $[0,1]$ that sums to one over $k$. Hard assignment is what $K$-means does.",
    ref: "Latent variable models & mixtures"
  },
  {
    id: "uns-3", type: "numeric", framing: "applied", difficulty: 2,
    prompt: "PCA is run on data whose sample covariance $\\hat{\\boldsymbol\\Sigma}$ has eigenvalues $\\lambda=(6,3,1)$. If you keep the top $L=2$ components, what <b>fraction of variance</b> $F_L=\\frac{\\sum_{j\\le L}\\lambda_j}{\\sum_j\\lambda_j}$ is retained?",
    answer: 0.9, tolerance: 0.01, unit: "",
    hint: "Sum the two largest eigenvalues over the total.",
    explanation: "$F_2=\\frac{6+3}{6+3+1}=\\frac{9}{10}=0.9$. Equivalently the reconstruction error is the discarded tail $\\sum_{j>L}\\lambda_j=1$, i.e. 10% of the total variance.",
    ref: "Principal components analysis (PCA)"
  },
  {
    id: "uns-4", type: "mc", framing: "applied", difficulty: 2,
    prompt: "Using the silhouette score $s(i)=\\frac{b_i-a_i}{\\max(a_i,b_i)}$, a point has mean intra-cluster distance $a_i=2$ and mean nearest-other-cluster distance $b_i=5$. What is $s(i)$?",
    options: ["0.6", "0.4", "3.0", "-0.6"],
    answer: 0,
    explanation: "$s(i)=\\frac{b_i-a_i}{\\max(a_i,b_i)}=\\frac{5-2}{5}=0.6$. Values near $+1$ mean the point sits comfortably inside its cluster and far from the next; the mean silhouette over all points is maximized to help choose $K$.",
    ref: "Clustering (choosing K)"
  },
  {
    id: "uns-5", type: "mc", framing: "conceptual", difficulty: 3,
    prompt: "During the <b>M-step</b> of EM for a GMM (with $r_k=\\sum_i r_{ik}$), how is the mixing weight updated?",
    options: [
      "$\\pi_k=r_k/N$",
      "$\\pi_k=r_k/K$",
      "$\\pi_k=1/K$ regardless of the data",
      "$\\pi_k=\\frac{\\sum_i r_{ik}\\boldsymbol{x}_i}{r_k}$"
    ],
    answer: 0,
    explanation: "The M-step sets $\\pi_k=\\tfrac{r_k}{N}$ — the share of total responsibility mass held by component $k$. The expression $\\frac{\\sum_i r_{ik}\\boldsymbol{x}_i}{r_k}$ is the update for the mean $\\boldsymbol\\mu_k$, not the weight.",
    ref: "EM for mixtures"
  },
  {
    id: "uns-6", type: "qc", framing: "applied", difficulty: 3,
    prompt: "Compare the <b>per-iteration computational cost</b> of the two clustering algorithms on $N$ points, $K$ clusters, and dimension $D>1$, as given in the K-means vs GMM table.",
    quantityA: "Per-iteration cost of $K$-means, $O(NKD)$",
    quantityB: "Per-iteration cost of a full-covariance GMM, $O(NKD^2)$",
    answer: 1,
    explanation: "$K$-means costs $O(NKD)$ per iteration while a full-covariance GMM costs $O(NKD^2)$. The extra factor of $D$ comes from forming and using the $D\\times D$ covariances $\\boldsymbol\\Sigma_k$. For $D>1$ the GMM cost is strictly greater, so B is larger.",
    ref: "Clustering (K-means vs GMM)"
  },
  {
    id: "uns-7", type: "ms", framing: "conceptual", difficulty: 4,
    prompt: "Select every statement that correctly characterizes <b>$K$-means</b> as described in the notes.",
    options: [
      "It minimizes the distortion $J=\\sum_n\\|\\boldsymbol{x}_n-\\boldsymbol\\mu_{z_n}\\|^2$",
      "It is hard EM on an <i>isotropic</i> (spherical) GMM",
      "$K$-means++ seeds centers with probability $\\propto D(\\boldsymbol{x})^2$",
      "It produces a soft, probabilistic assignment $r_{ik}$ for each point",
      "It fits ellipsoidal clusters with a per-cluster covariance $\\boldsymbol\\Sigma_k$"
    ],
    answer: [0, 1, 2],
    explanation: "$K$-means minimizes distortion $J$ via Lloyd's alternation and is exactly hard EM on an isotropic GMM; $K$-means++ seeds centers $\\propto D(\\boldsymbol{x})^2$ for an $O(\\log K)$ improvement. Soft assignments $r_{ik}$ and ellipsoidal per-cluster covariances belong to the GMM, not $K$-means (which is hard and spherical).",
    ref: "Clustering"
  },
  {
    id: "uns-8", type: "numeric", framing: "applied", difficulty: 4,
    prompt: "In <b>probabilistic PCA</b> the noise variance is estimated as $\\hat\\sigma^2=\\frac{1}{D-L}\\sum_{j>L}\\lambda_j$. With data dimension $D=5$, retained components $L=2$, and the discarded eigenvalues $\\lambda_3=0.6,\\ \\lambda_4=0.3,\\ \\lambda_5=0.3$, compute $\\hat\\sigma^2$.",
    answer: 0.4, tolerance: 0.01, unit: "",
    hint: "Average the discarded eigenvalues over $D-L=3$.",
    explanation: "$\\hat\\sigma^2=\\frac{1}{D-L}\\sum_{j>L}\\lambda_j=\\frac{0.6+0.3+0.3}{5-2}=\\frac{1.2}{3}=0.4$ — the average variance left in the discarded directions. As $\\sigma^2\\to0$, PPCA recovers classical PCA.",
    ref: "Probabilistic PCA"
  },
  {
    id: "uns-9", type: "ms", framing: "conceptual", difficulty: 5,
    prompt: "Select every statement about <b>factor analysis (FA)</b> and its relatives that is correct per the notes.",
    options: [
      "FA assumes $p(\\boldsymbol{z})=\\mathcal{N}(\\mathbf{0},\\mathbf{I})$ and $p(\\boldsymbol{x}\\mid\\boldsymbol{z})=\\mathcal{N}(\\mathbf{W}\\boldsymbol{z}+\\boldsymbol\\mu,\\boldsymbol\\Psi)$ with <i>diagonal</i> $\\boldsymbol\\Psi$",
      "The marginal covariance $\\mathbf{C}=\\mathbf{W}\\mathbf{W}^\\top+\\boldsymbol\\Psi$ is low-rank-plus-diagonal",
      "Probabilistic PCA is the special case of FA with $\\boldsymbol\\Psi=\\sigma^2\\mathbf{I}$",
      "The loading matrix $\\mathbf{W}$ is identified uniquely, with no rotational ambiguity",
      "A VAE is a nonlinear FA with neural-network encoder and decoder"
    ],
    answer: [0, 1, 2, 4],
    explanation: "FA uses a standard-normal latent and Gaussian noise with diagonal $\\boldsymbol\\Psi$, giving marginal covariance $\\mathbf{W}\\mathbf{W}^\\top+\\boldsymbol\\Psi$ (low-rank plus diagonal). PPCA is FA with isotropic $\\boldsymbol\\Psi=\\sigma^2\\mathbf{I}$, and a VAE is nonlinear FA. The false claim is uniqueness: $\\mathbf{W}$ is identified only up to a rotation.",
    ref: "Factor analysis & ICA"
  },
  {
    id: "uns-10", type: "mc", framing: "conceptual", difficulty: 5,
    prompt: "In <b>ICA</b> (blind source separation), why is the <b>non-Gaussianity</b> of the sources essential?",
    options: [
      "It is what makes the individual sources recoverable; with Gaussian sources only the subspace is identified, as in PCA",
      "It guarantees the sign and permutation of recovered sources are uniquely determined",
      "It allows the sources to be correlated rather than independent",
      "It makes the mixing matrix $\\mathbf{W}$ symmetric and easy to invert"
    ],
    answer: 0,
    explanation: "Non-Gaussianity is precisely what lets ICA recover individual sources — for Gaussian sources the rotation is unidentifiable and you recover only the subspace, exactly like PCA. After whitening, maximizing non-Gaussianity $\\equiv$ minimizing mutual information $\\equiv$ MLE $\\equiv$ infomax. Sign and permutation, however, remain unidentifiable.",
    ref: "Factor analysis & ICA"
  }
];
